const fs=require("fs");const path=require("path");const pino=require("pino");const{default:makeWASocket,useMultiFileAuthState,fetchLatestBaileysVersion,DisconnectReason}=require("@whiskeysockets/baileys");
const ROOT="./subbots";const META=path.join(ROOT,"subbots.json");let sockets=new Map();
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function ensure(){fs.mkdirSync(ROOT,{recursive:true});if(!fs.existsSync(META))fs.writeFileSync(META,JSON.stringify({bots:{}},null,2))}
function read(){ensure();try{return JSON.parse(fs.readFileSync(META,"utf8"))}catch{return{bots:{}}}}
function write(d){ensure();fs.writeFileSync(META,JSON.stringify(d,null,2))}
function safe(n){return String(n||"").toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,32)}
const DEFAULT_BLOCKED=["subbot","restart","shutdown","update","reload","addprem","delprem"];
function isCommandAllowed(id,command){const b=read().bots[id];if(!b)return false;const c=String(command||"").toLowerCase();if(b.allowedCommands?.length)return b.allowedCommands.includes(c);return !DEFAULT_BLOCKED.includes(c)}
function setAllowedCommands(id,commands){const d=read();if(!d.bots[id])return false;d.bots[id].allowedCommands=[...new Set(commands.map(x=>String(x).toLowerCase().replace(/^\//,"")).filter(Boolean))];write(d);return true}
function getCommandPolicy(id){return read().bots[id]?.allowedCommands||null}
function list(){return Object.values(read().bots)}
function bind(id,sock,saveCreds,onMessage){sockets.set(id,sock);sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",u=>{const x=read();if(x.bots[id]){if(u.connection==="open")x.bots[id].status="online";else if(u.connection==="close")x.bots[id].status="offline";else x.bots[id].status="starting";if(u.connection==="close"&&u.lastDisconnect)console.error("Subbot "+id+" desconectado:",u.lastDisconnect.error?.message||"connection closed");write(x)}if(u.connection==="close")sockets.delete(id)});sock.ev.on("messages.upsert",async m=>{try{const msg=m.messages?.[0];if(msg&&onMessage)await onMessage(id,sock,msg)}catch(e){console.error("Subbot "+id+":",e.message)}})}
async function create(name,phone,onMessage){ensure();const id=safe(name);if(!id)throw Error("Nombre inválido");const clean=String(phone||"").replace(/\D/g,"");if(clean.length<8||clean.length>15)throw Error("Número inválido. Usa el número completo con código de país.");const d=read();if(d.bots[id])throw Error("Ese subbot ya existe");const dir=path.join(ROOT,id,"sessions");fs.mkdirSync(dir,{recursive:true});const{state,saveCreds}=await useMultiFileAuthState(dir);const{version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:"silent"}),browser:["ONYX-BOT","Chrome","1.0.0"]});const bot={id,name:id,phone:clean,status:"pairing",createdAt:new Date().toISOString()};d.bots[id]=bot;write(d);bind(id,sock,saveCreds,onMessage);console.log("🤖 Creando subbot:",id,"con número",clean);
if(state.creds.registered)return bot;
try{await delay(2500);if(state.creds.registered)return bot;const code=await Promise.race([sock.requestPairingCode(clean),new Promise((_,reject)=>setTimeout(()=>reject(Error("No se pudo obtener el código de emparejamiento a tiempo")),20000))]);bot.pairingCode=code;bot.status="pairing";write(read());console.log("📲 Pairing code generado para",id,":",code);return bot}catch(e){console.error("❌ Error creando subbot "+id+":",e.message);try{sock.end(undefined)}catch{}sockets.delete(id);const x=read();delete x.bots[id];write(x);throw e}}
async function stop(id){const sock=sockets.get(id);if(sock){try{sock.end(undefined)}catch{}sockets.delete(id)}const d=read();if(d.bots[id]){d.bots[id].status="offline";write(d)}}
async function remove(id){await stop(id);const d=read();if(!d.bots[id])return false;delete d.bots[id];write(d);return true}
async function startExisting(id,onMessage){const d=read(),bot=d.bots[id];if(!bot)return null;const dir=path.join(ROOT,id,"sessions");if(!fs.existsSync(path.join(dir,"creds.json"))){bot.status="pairing";write(d);return bot}const{state,saveCreds}=await useMultiFileAuthState(dir);const{version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:"silent"}),browser:["ONYX-BOT","Chrome","1.0.0"]});bind(id,sock,saveCreds,onMessage);return bot}
module.exports={create,stop,remove,list,startExisting,isCommandAllowed,setAllowedCommands,getCommandPolicy};