const fs=require("fs");const path=require("path");const pino=require("pino");const{default:makeWASocket,useMultiFileAuthState,fetchLatestBaileysVersion}=require("@whiskeysockets/baileys");
const ROOT="./subbots";const META=path.join(ROOT,"subbots.json");let sockets=new Map();
function ensure(){fs.mkdirSync(ROOT,{recursive:true});if(!fs.existsSync(META))fs.writeFileSync(META,JSON.stringify({bots:{}},null,2))}
function read(){ensure();try{return JSON.parse(fs.readFileSync(META,"utf8"))}catch{return{bots:{}}}}
function write(d){ensure();fs.writeFileSync(META,JSON.stringify(d,null,2))}
function safe(n){return String(n||"").toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,32)}
const DEFAULT_BLOCKED=["subbot","restart","shutdown","update","reload","addprem","delprem"];
function isCommandAllowed(id,command){const b=read().bots[id];if(!b)return false;const c=String(command||"").toLowerCase();if(b.allowedCommands?.length)return b.allowedCommands.includes(c);return !DEFAULT_BLOCKED.includes(c)}
function setAllowedCommands(id,commands){const d=read();if(!d.bots[id])return false;d.bots[id].allowedCommands=[...new Set(commands.map(x=>String(x).toLowerCase().replace(/^\//,"")).filter(Boolean))];write(d);return true}
function getCommandPolicy(id){const b=read().bots[id];return b?.allowedCommands||null}
function list(){return Object.values(read().bots)}
async function create(name,phone,onMessage){ensure();const id=safe(name);if(!id)throw Error("Nombre inválido");const d=read();if(d.bots[id])throw Error("Ese subbot ya existe");const dir=path.join(ROOT,id,"sessions");fs.mkdirSync(dir,{recursive:true});const{state,saveCreds}=await useMultiFileAuthState(dir);const{version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:"silent"})});const bot={id,name:id,phone:String(phone).replace(/\D/g,""),status:"starting",createdAt:new Date().toISOString()};d.bots[id]=bot;write(d);sockets.set(id,sock);sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",u=>{const x=read();if(x.bots[id]){x.bots[id].status=u.connection==="open"?"online":u.connection==="close"?"offline":"starting";write(x)}if(u.connection==="close")sockets.delete(id)});sock.ev.on("messages.upsert",async m=>{try{const msg=m.messages?.[0];if(msg&&onMessage)await onMessage(id,sock,msg)}catch(e){console.error("Subbot",id,e.message)}});if(!fs.existsSync(path.join(dir,"creds.json"))&&bot.phone){bot.pairingCode=await sock.requestPairingCode(bot.phone);d.bots[id]=bot;write(d)}return bot}
async function stop(id){const sock=sockets.get(id);if(sock){try{sock.end(undefined)}catch{}sockets.delete(id)}const d=read();if(d.bots[id]){d.bots[id].status="offline";write(d)}}
async function remove(id){await stop(id);const d=read();if(!d.bots[id])return false;delete d.bots[id];write(d);return true}
async function startExisting(id,onMessage){const d=read(),bot=d.bots[id];if(!bot)return null;const dir=path.join(ROOT,id,"sessions");if(!fs.existsSync(path.join(dir,"creds.json")))return bot;const{state,saveCreds}=await useMultiFileAuthState(dir);const{version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:"silent"})});sockets.set(id,sock);sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",u=>{const x=read();if(x.bots[id]){x.bots[id].status=u.connection==="open"?"online":u.connection==="close"?"offline":"starting";write(x)}if(u.connection==="close")sockets.delete(id)});sock.ev.on("messages.upsert",async m=>{try{const msg=m.messages?.[0];if(msg&&onMessage)await onMessage(id,sock,msg)}catch(e){console.error("Subbot",id,e.message)}});return bot}
module.exports={create,stop,remove,list,startExisting,isCommandAllowed,setAllowedCommands,getCommandPolicy};