const{esOwner}=require("../sistemas/premium");const{create,stop,remove,list,startExisting,isCommandAllowed,setAllowedCommands,getCommandPolicy}=require("../subbots/manager");
function commandFromMessage(msg){const body=msg?.message?.conversation||msg?.message?.extendedTextMessage?.text||msg?.message?.imageMessage?.caption||msg?.message?.videoMessage?.caption||"";return body.trim().split(/\s+/)[0].replace(/^\//,"").toLowerCase()}
async function routeSubbot(id,sock,msg){try{const command=commandFromMessage(msg);if(!isCommandAllowed(id,command)){const jid=msg.key.remoteJid;return sock.sendMessage(jid,{text:"🔒 Este comando está bloqueado para este subbot."},{quoted:msg})}const main=require("../main.js");await main.handleMessage(sock,msg)}catch(e){console.error("Subbot "+id+":",e.message)}}
async function handler(conn,{message,args}){const jid=message.key.remoteJid;const sender=[message.key.participant,message.key.participantAlt,message.key.remoteJid,message.key.remoteJidAlt].filter(Boolean);if(!esOwner(sender)){try{const lids=sender.filter(x=>String(x).endsWith("@lid"));for(const lid of lids){const pn=await conn.signalRepository?.lidMapping?.getPNForLID(lid);if(pn&&esOwner(pn)){sender.push(pn);break}}}catch{} }if(!esOwner(sender))return conn.sendMessage(jid,{text:"⛔ Solo el owner puede administrar subbots."},{quoted:message});const sub=(args.shift()||"").toLowerCase();
if(sub==="list"){const bots=list();return conn.sendMessage(jid,{text:bots.length?"🤖 SUBBOTS\n\n"+bots.map(b=>"• "+b.name+": "+b.status+" | "+(b.allowedCommands?.length?b.allowedCommands.join(", "):"modo estándar")).join("\n"):"🤖 No hay subbots registrados."},{quoted:message})}
if(sub==="create"){const name=args.shift(),phone=args.shift();if(!name||!phone)return conn.sendMessage(jid,{text:"Uso: /subbot create <nombre> <número>"},{quoted:message});try{const b=await create(name,phone,routeSubbot);return conn.sendMessage(jid,{text:"🤖 Subbot "+b.name+" creado.\n📲 Código de emparejamiento: "+(b.pairingCode||"sesión existente")+"\n\n🔒 Comandos sensibles bloqueados por defecto."},{quoted:message})}catch(e){return conn.sendMessage(jid,{text:"❌ "+e.message},{quoted:message})}}
if(sub==="start"){const name=args.shift();if(!name)return conn.sendMessage(jid,{text:"Uso: /subbot start <nombre>"},{quoted:message});try{const b=await startExisting(name,routeSubbot);return conn.sendMessage(jid,{text:b?"▶️ Subbot "+name+" iniciado.":"❌ Subbot no encontrado."},{quoted:message})}catch(e){return conn.sendMessage(jid,{text:"❌ "+e.message},{quoted:message})}}
if(sub==="stop"){const name=args.shift();if(!name)return conn.sendMessage(jid,{text:"Uso: /subbot stop <nombre>"},{quoted:message});await stop(name);return conn.sendMessage(jid,{text:"🛑 Subbot detenido."},{quoted:message})}
if(sub==="remove"){const name=args.shift();if(!name)return conn.sendMessage(jid,{text:"Uso: /subbot remove <nombre>"},{quoted:message});const ok=await remove(name);return conn.sendMessage(jid,{text:ok?"🗑️ Subbot eliminado del registro.":"❌ Subbot no encontrado."},{quoted:message})}
if(sub==="allow"||sub==="deny"){const name=args.shift(),cmd=(args.shift()||"").replace(/^\//,"").toLowerCase();if(!name||!cmd)return conn.sendMessage(jid,{text:"Uso: /subbot "+sub+" <nombre> <comando>"},{quoted:message});const current=getCommandPolicy(name)||[];let next=sub==="allow"?[...current,cmd]:current.filter(x=>x!==cmd);if(sub==="allow"&&!current.length){next=[cmd]}const ok=setAllowedCommands(name,next);return conn.sendMessage(jid,{text:ok?"🔐 Permisos actualizados para "+name+".\nPermitidos: "+(next.length?next.join(", "):"ninguno"):"❌ Subbot no encontrado."},{quoted:message})}
if(sub==="commands"){const name=args.shift();if(!name)return conn.sendMessage(jid,{text:"Uso: /subbot commands <nombre>"},{quoted:message});const p=getCommandPolicy(name);return conn.sendMessage(jid,{text:p?("🔐 Comandos permitidos de "+name+":\n"+p.join(", ")):("🔒 "+name+" usa la política estándar.\nBloqueados: subbot, restart, shutdown, update, reload, addprem, delprem")},{quoted:message})}
return conn.sendMessage(jid,{text:"🤖 SUBBOT\n/subbot list\n/subbot create <nombre> <número>\n/subbot start <nombre>\n/subbot stop <nombre>\n/subbot remove <nombre>\n/subbot allow <nombre> <comando>\n/subbot deny <nombre> <comando>\n/subbot commands <nombre>"},{quoted:message})}
module.exports={command:"subbot",handler};